# Generated by Django 4.2.1 on 2024-08-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_name',
        ),
    ]
